{
 "title": "Flink",
 "description": "Flink Monitoring Dashboard - Explanation of the metrics:\n\n- https://docs.datadoghq.com/integrations/flink/#data-collected\n- https://ci.apache.org/projects/flink/flink-docs-stable/ops/metrics.html",
 "tags": [
  "flink",
  "monitoring"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "app_name",
    "query": {
     "query": "label_values(flink_jobmanager_numRegisteredTaskManagers, app_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Registered Task Managers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_jobmanager_numRegisteredTaskManagers{app_name=~\"$app_name\"})"
    }
   ]
  },
  {
   "title": "Number of Total Task Slots",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_jobmanager_taskSlotsTotal{app_name=~\"$app_name\"})"
    }
   ]
  },
  {
   "title": "Last Checkpoint Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(flink_jobmanager_job_lastCheckpointSize{app_name=~\"$app_name\"})"
    }
   ]
  },
  {
   "title": "Job Manager Restarts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(flink_jobmanager_job_restartingTime{app_name=~\"$app_name\"})"
    }
   ]
  },
  {
   "title": "Job Manager Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(flink_jobmanager_job_uptime{app_name=~\"$app_name\"})"
    }
   ]
  },
  { "title": "Job Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Flink Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(flink_jobmanager_Status_JVM_Memory_Heap_Used{app_name=~\"$app_name\"}) by (host)",
     "legendFormat": "Heap Used - {{host}}"
    },
    {
     "expr": "avg(flink_jobmanager_Status_JVM_Memory_Heap_Max{app_name=~\"$app_name\"}) by (host)",
     "legendFormat": "Heap Max - {{host}}"
    },
    {
     "expr": "avg(flink_jobmanager_Status_JVM_Memory_NonHeap_Used{app_name=~\"$app_name\"}) by (host)",
     "legendFormat": "NonHeap Used - {{host}}"
    },
    {
     "expr": "avg(flink_jobmanager_Status_JVM_Memory_Direct_MemoryUsed{app_name=~\"$app_name\"}) by (host)",
     "legendFormat": "Direct Memory - {{host}}"
    }
   ]
  },
  {
   "title": "Cumulative JVM GC Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(flink_jobmanager_Status_JVM_GarbageCollector_Copy_Time{app_name=~\"$app_name\"}) by (host)",
     "legendFormat": "Copy - {{host}}"
    },
    {
     "expr": "avg(flink_jobmanager_Status_JVM_GarbageCollector_MarkSweepCompact_Time{app_name=~\"$app_name\"}) by (host)",
     "legendFormat": "MarkSweepCompact - {{host}}"
    },
    {
     "expr": "avg(flink_jobmanager_Status_JVM_GarbageCollector_G1_Young_Generation_Time{app_name=~\"$app_name\"}) by (host)",
     "legendFormat": "G1 Young - {{host}}"
    },
    {
     "expr": "avg(flink_jobmanager_Status_JVM_GarbageCollector_G1_Old_Generation_Time{app_name=~\"$app_name\"}) by (host)",
     "legendFormat": "G1 Old - {{host}}"
    }
   ]
  },
  { "title": "Task Managers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Flink Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(flink_taskmanager_Status_JVM_Memory_Heap_Used{app_name=~\"$app_name\"}) by (host)",
     "legendFormat": "Heap Used - {{host}}"
    },
    {
     "expr": "avg(flink_taskmanager_Status_JVM_Memory_Heap_Max{app_name=~\"$app_name\"}) by (host)",
     "legendFormat": "Heap Max - {{host}}"
    },
    {
     "expr": "avg(flink_taskmanager_Status_JVM_Memory_NonHeap_Used{app_name=~\"$app_name\"}) by (host)",
     "legendFormat": "NonHeap Used - {{host}}"
    },
    {
     "expr": "avg(flink_taskmanager_Status_JVM_Memory_Direct_MemoryUsed{app_name=~\"$app_name\"}) by (host)",
     "legendFormat": "Direct Memory - {{host}}"
    }
   ]
  },
  {
   "title": "Cumulative JVM GC Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(flink_taskmanager_Status_JVM_GarbageCollector_Copy_Time{app_name=~\"$app_name\"}) by (host)",
     "legendFormat": "Copy - {{host}}"
    },
    {
     "expr": "avg(flink_taskmanager_Status_JVM_GarbageCollector_MarkSweepCompact_Time{app_name=~\"$app_name\"}) by (host)",
     "legendFormat": "MarkSweepCompact - {{host}}"
    },
    {
     "expr": "avg(flink_taskmanager_Status_JVM_GarbageCollector_G1_Young_Generation_Time{app_name=~\"$app_name\"}) by (host)",
     "legendFormat": "G1 Young - {{host}}"
    },
    {
     "expr": "avg(flink_taskmanager_Status_JVM_GarbageCollector_G1_Old_Generation_Time{app_name=~\"$app_name\"}) by (host)",
     "legendFormat": "G1 Old - {{host}}"
    }
   ]
  },
  {
   "title": "Time % Backpressured By Task",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(max(flink_taskmanager_job_task_backPressuredTimeMsPerSecond{app_name=~\"$app_name\"}) by (task_name) / 1000) * 100",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Bytes In By Task",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_numBytesInPerSecond{app_name=~\"$app_name\"}) by (task_name, task_id)",
     "legendFormat": "{{task_name}} - {{task_id}}"
    }
   ]
  },
  {
   "title": "Records In By Task",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_numRecordsInPerSecond{app_name=~\"$app_name\"}) by (task_name, task_id)",
     "legendFormat": "{{task_name}} - {{task_id}}"
    }
   ]
  },
  {
   "title": "Bytes Out By Task",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_numBytesOutPerSecond{app_name=~\"$app_name\"}) by (task_name, task_id)",
     "legendFormat": "{{task_name}} - {{task_id}}"
    }
   ]
  },
  {
   "title": "Records Out By Task",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_numRecordsOutPerSecond{app_name=~\"$app_name\"}) by (task_name, task_id)",
     "legendFormat": "{{task_name}} - {{task_id}}"
    }
   ]
  },
  { "title": "Checkpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Completed Checkpoints Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(flink_jobmanager_job_numberOfCompletedCheckpoints{app_name=~\"$app_name\"}[10m])",
     "legendFormat": "Completed Checkpoints"
    }
   ]
  },
  {
   "title": "Failed Checkpoints Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(flink_jobmanager_job_numberOfFailedCheckpoints{app_name=~\"$app_name\"}[10m])",
     "legendFormat": "Failed Checkpoints"
    }
   ]
  },
  {
   "title": "Last Checkpoint Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(flink_jobmanager_job_lastCheckpointDuration{app_name=~\"$app_name\"})",
     "legendFormat": "Last Checkpoint Duration"
    }
   ]
  },
  { "title": "Kafka Consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Kafka Consumer Records Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(flink_operator_KafkaSourceReader_KafkaConsumer_records_consumed_rate{app_name=~\"$app_name\"}) by (task_name, task_id)",
     "legendFormat": "{{task_name}} - {{task_id}}"
    }
   ]
  },
  {
   "title": "Kafka Consumer Bytes Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(flink_operator_KafkaSourceReader_KafkaConsumer_bytes_consumed_rate{app_name=~\"$app_name\"}) by (task_name, task_id)",
     "legendFormat": "{{task_name}} - {{task_id}}"
    }
   ]
  },
  {
   "title": "Records Lag",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(flink_operator_KafkaSourceReader_KafkaConsumer_records_lag_max{app_name=~\"$app_name\"}) by (operator_name)",
     "legendFormat": "{{operator_name}}"
    }
   ]
  }
 ]
}